version: '2.24'

services:
  
  wordpress:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    container_name: wp-wordpress
    restart: always
    # network_mode: host
    ports:
      - ${WP_PORT}:80 # change ip if required
    volumes:
      - ./config/wp_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
    environment:
      WORDPRESS_DB_HOST: ${LAN_IP}
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:5  # https://hub.docker.com/_/phpmyadmin
    container_name: wp-phpmyadmin
    restart: always
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: ${LAN_IP}
    volumes:
      - ./config/pma_php.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./config/pma_config.php:/etc/phpmyadmin/config.user.inc.php
    depends_on:
      - db
    ports:
      - ${PHPMyAdmin_PORT}:80
  
  db:
    image: mariadb:10.6 
    container_name: wp-db
    restart: always
    ports:
      - 3306:3306 
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

